plugins:
  chat_bridge_enabled:
    default: false
    client: true
  chat_telegram_bridges:
    default: ""
    type: list
    client: false
  chat_telegram_bridge_secret_path:
    default: ""
    hidden: true
    client: false
